[package]
name = "candy"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# [build-dependencies]
# bootimage = "0.10.3"

# [package.metadata.bootimage]
# target = "x86_64-unknown-none"